services:
  api:
    build: ./app
    env_file:
      - .env
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"

  db:
    image: postgres:16
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}

  adminer:
    image: adminer:latest
    restart: always
    networks:
      - default
    depends_on:
      - db
    environment:
      ADMINER_DESIGN: dracula
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DEFAULT_TYPE: pgsql
      ADMINER_DEFAULT_PORT: 5432
    ports:
      - "8080:8080"

volumes:
  postgres_data:
